# Generated by Django 3.0.3 on 2020-05-22 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=20)),
                ('fecha_vencimiento', models.DateField()),
                ('contrato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.Contrato')),
            ],
        ),
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lectura_actual', models.DecimalField(decimal_places=1, max_digits=300)),
                ('lectura_anterior', models.DecimalField(decimal_places=1, max_digits=300)),
                ('fecha_lectura', models.DateField(auto_now=True)),
                ('contador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Contador')),
            ],
        ),
    ]
