# Generated by Django 3.0.3 on 2020-05-21 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subestaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transformador',
            fields=[
                ('serial', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('marca', models.CharField(max_length=30)),
                ('devanado', models.CharField(choices=[('elevador', 'Elevador'), ('reductor', 'Reductor')], default='elevador', max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('subestacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subestaciones.Subestacion')),
            ],
        ),
    ]
